<?php

declare(strict_types=1);

namespace ProcessWire;

class TextformatterCookieTable extends Textformatter implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title' => 'CookieMonster Textformatter',
            'version' => 104,
            'summary' => 'Uses a shortcode to render a table with your configured cookies',
            'author' => 'Johannes Dachsel'
        );
    }

    public function formatValue(Page $page, Field $field, &$str): void
    {
        /** @var CookieMonster|null $cmnstr */
        $cmnstr = $this->modules->get('CookieMonster');

        $needle = '[[cookie-table]]';
        if (strpos($str, $needle) !== false) {
            $output = $cmnstr->renderCookieTable();
            $str = str_replace($needle, $output, $str);
        }

        $needle = '[[cookie-list]]';
        if (strpos($str, $needle) !== false) {
            $output = $cmnstr->renderCookieList();
            $str = str_replace($needle, $output, $str);
        }
    }
}
